// Code generated by protoc-gen-fieldmask. DO NOT EDIT.
// source: api/v1/common/common.proto
package common

var localMemosApiV1CommonPageTokenFieldMaskPaths = newMemosApiV1CommonPageTokenFieldMaskPaths("", 2)

func (x *PageToken) FieldMaskPaths() memosApiV1CommonPageTokenIntFieldMaskPaths {
	return localMemosApiV1CommonPageTokenFieldMaskPaths
}

type memosApiV1CommonPageTokenIntFieldMaskPaths interface {
	Limit() string
	Offset() string
}

type memosApiV1CommonPageTokenFieldMaskPaths struct {
	fieldPath string
	prefix    string
	limit     string
	offset    string
}

func newMemosApiV1CommonPageTokenFieldMaskPaths(fieldPath string, maxDepth int) *memosApiV1CommonPageTokenFieldMaskPaths {
	if maxDepth <= 0 {
		return nil
	}
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return &memosApiV1CommonPageTokenFieldMaskPaths{
		fieldPath: fieldPath,
		prefix:    prefix,
		limit:     prefix + "limit",
		offset:    prefix + "offset",
	}
}

func (x *memosApiV1CommonPageTokenFieldMaskPaths) String() string { return x.fieldPath }
func (x *memosApiV1CommonPageTokenFieldMaskPaths) Limit() string  { return x.limit }
func (x *memosApiV1CommonPageTokenFieldMaskPaths) Offset() string { return x.offset }
