// Code generated by protoc-gen-fieldmask. DO NOT EDIT.
// source: api/v1/resources/resource_service.proto
package resources

var localMemosApiV1ResourcesResourceFieldMaskPaths = newMemosApiV1ResourcesResourceFieldMaskPaths("", 2)
var localMemosApiV1ResourcesCreateResourceRequestFieldMaskPaths = newMemosApiV1ResourcesCreateResourceRequestFieldMaskPaths("", 2)
var localMemosApiV1ResourcesListResourcesResponseFieldMaskPaths = newMemosApiV1ResourcesListResourcesResponseFieldMaskPaths("", 2)
var localMemosApiV1ResourcesGetResourceRequestFieldMaskPaths = newMemosApiV1ResourcesGetResourceRequestFieldMaskPaths("", 2)
var localMemosApiV1ResourcesGetResourceByUidRequestFieldMaskPaths = newMemosApiV1ResourcesGetResourceByUidRequestFieldMaskPaths("", 2)
var localMemosApiV1ResourcesGetResourceBinaryRequestFieldMaskPaths = newMemosApiV1ResourcesGetResourceBinaryRequestFieldMaskPaths("", 2)
var localMemosApiV1ResourcesUpdateResourceRequestFieldMaskPaths = newMemosApiV1ResourcesUpdateResourceRequestFieldMaskPaths("", 2)
var localMemosApiV1ResourcesDeleteResourceRequestFieldMaskPaths = newMemosApiV1ResourcesDeleteResourceRequestFieldMaskPaths("", 2)

func (x *Resource) FieldMaskPaths() memosApiV1ResourcesResourceIntFieldMaskPaths {
	return localMemosApiV1ResourcesResourceFieldMaskPaths
}
func (x *CreateResourceRequest) FieldMaskPaths() memosApiV1ResourcesCreateResourceRequestIntFieldMaskPaths {
	return localMemosApiV1ResourcesCreateResourceRequestFieldMaskPaths
}
func (x *ListResourcesResponse) FieldMaskPaths() memosApiV1ResourcesListResourcesResponseIntFieldMaskPaths {
	return localMemosApiV1ResourcesListResourcesResponseFieldMaskPaths
}
func (x *GetResourceRequest) FieldMaskPaths() memosApiV1ResourcesGetResourceRequestIntFieldMaskPaths {
	return localMemosApiV1ResourcesGetResourceRequestFieldMaskPaths
}
func (x *GetResourceByUidRequest) FieldMaskPaths() memosApiV1ResourcesGetResourceByUidRequestIntFieldMaskPaths {
	return localMemosApiV1ResourcesGetResourceByUidRequestFieldMaskPaths
}
func (x *GetResourceBinaryRequest) FieldMaskPaths() memosApiV1ResourcesGetResourceBinaryRequestIntFieldMaskPaths {
	return localMemosApiV1ResourcesGetResourceBinaryRequestFieldMaskPaths
}
func (x *UpdateResourceRequest) FieldMaskPaths() memosApiV1ResourcesUpdateResourceRequestIntFieldMaskPaths {
	return localMemosApiV1ResourcesUpdateResourceRequestFieldMaskPaths
}
func (x *DeleteResourceRequest) FieldMaskPaths() memosApiV1ResourcesDeleteResourceRequestIntFieldMaskPaths {
	return localMemosApiV1ResourcesDeleteResourceRequestFieldMaskPaths
}

type memosApiV1ResourcesResourceIntFieldMaskPaths interface {
	Name() string
	Uid() string
	Filename() string
	Content() string
	ExternalLink() string
	Size() string
	CreateTime() *googleProtobufTimestampFieldMaskPaths
}

type memosApiV1ResourcesResourceFieldMaskPaths struct {
	fieldPath    string
	prefix       string
	name         string
	uid          string
	filename     string
	content      string
	externalLink string
	size         string
	createTime   *googleProtobufTimestampFieldMaskPaths
}

func newMemosApiV1ResourcesResourceFieldMaskPaths(fieldPath string, maxDepth int) *memosApiV1ResourcesResourceFieldMaskPaths {
	if maxDepth <= 0 {
		return nil
	}
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return &memosApiV1ResourcesResourceFieldMaskPaths{
		fieldPath:    fieldPath,
		prefix:       prefix,
		name:         prefix + "name",
		uid:          prefix + "uid",
		filename:     prefix + "filename",
		content:      prefix + "content",
		externalLink: prefix + "external_link",
		size:         prefix + "size",
		createTime:   newGoogleProtobufTimestampFieldMaskPaths(prefix+"create_time", maxDepth-1),
	}
}

func (x *memosApiV1ResourcesResourceFieldMaskPaths) String() string       { return x.fieldPath }
func (x *memosApiV1ResourcesResourceFieldMaskPaths) Name() string         { return x.name }
func (x *memosApiV1ResourcesResourceFieldMaskPaths) Uid() string          { return x.uid }
func (x *memosApiV1ResourcesResourceFieldMaskPaths) Filename() string     { return x.filename }
func (x *memosApiV1ResourcesResourceFieldMaskPaths) Content() string      { return x.content }
func (x *memosApiV1ResourcesResourceFieldMaskPaths) ExternalLink() string { return x.externalLink }
func (x *memosApiV1ResourcesResourceFieldMaskPaths) Size() string         { return x.size }
func (x *memosApiV1ResourcesResourceFieldMaskPaths) CreateTime() *googleProtobufTimestampFieldMaskPaths {
	if x.createTime != nil {
		return x.createTime
	}
	return newGoogleProtobufTimestampFieldMaskPaths(x.prefix+"create_time", 2)
}

type googleProtobufTimestampFieldMaskPaths struct {
	fieldPath string
	prefix    string
	seconds   string
	nanos     string
}

func newGoogleProtobufTimestampFieldMaskPaths(fieldPath string, maxDepth int) *googleProtobufTimestampFieldMaskPaths {
	if maxDepth <= 0 {
		return nil
	}
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return &googleProtobufTimestampFieldMaskPaths{
		fieldPath: fieldPath,
		prefix:    prefix,
		seconds:   prefix + "seconds",
		nanos:     prefix + "nanos",
	}
}

func (x *googleProtobufTimestampFieldMaskPaths) String() string  { return x.fieldPath }
func (x *googleProtobufTimestampFieldMaskPaths) Seconds() string { return x.seconds }
func (x *googleProtobufTimestampFieldMaskPaths) Nanos() string   { return x.nanos }

type memosApiV1ResourcesCreateResourceRequestIntFieldMaskPaths interface {
	Resource() *memosApiV1ResourcesResourceFieldMaskPaths
}

type memosApiV1ResourcesCreateResourceRequestFieldMaskPaths struct {
	fieldPath string
	prefix    string
	resource  *memosApiV1ResourcesResourceFieldMaskPaths
}

func newMemosApiV1ResourcesCreateResourceRequestFieldMaskPaths(fieldPath string, maxDepth int) *memosApiV1ResourcesCreateResourceRequestFieldMaskPaths {
	if maxDepth <= 0 {
		return nil
	}
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return &memosApiV1ResourcesCreateResourceRequestFieldMaskPaths{
		fieldPath: fieldPath,
		prefix:    prefix,
		resource:  newMemosApiV1ResourcesResourceFieldMaskPaths(prefix+"resource", maxDepth-1),
	}
}

func (x *memosApiV1ResourcesCreateResourceRequestFieldMaskPaths) String() string { return x.fieldPath }
func (x *memosApiV1ResourcesCreateResourceRequestFieldMaskPaths) Resource() *memosApiV1ResourcesResourceFieldMaskPaths {
	if x.resource != nil {
		return x.resource
	}
	return newMemosApiV1ResourcesResourceFieldMaskPaths(x.prefix+"resource", 2)
}

type memosApiV1ResourcesListResourcesResponseIntFieldMaskPaths interface {
	Resources() string
}

type memosApiV1ResourcesListResourcesResponseFieldMaskPaths struct {
	fieldPath string
	prefix    string
	resources string
}

func newMemosApiV1ResourcesListResourcesResponseFieldMaskPaths(fieldPath string, maxDepth int) *memosApiV1ResourcesListResourcesResponseFieldMaskPaths {
	if maxDepth <= 0 {
		return nil
	}
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return &memosApiV1ResourcesListResourcesResponseFieldMaskPaths{
		fieldPath: fieldPath,
		prefix:    prefix,
		resources: prefix + "resources",
	}
}

func (x *memosApiV1ResourcesListResourcesResponseFieldMaskPaths) String() string { return x.fieldPath }
func (x *memosApiV1ResourcesListResourcesResponseFieldMaskPaths) Resources() string {
	return x.resources
}

type memosApiV1ResourcesGetResourceRequestIntFieldMaskPaths interface {
	Name() string
}

type memosApiV1ResourcesGetResourceRequestFieldMaskPaths struct {
	fieldPath string
	prefix    string
	name      string
}

func newMemosApiV1ResourcesGetResourceRequestFieldMaskPaths(fieldPath string, maxDepth int) *memosApiV1ResourcesGetResourceRequestFieldMaskPaths {
	if maxDepth <= 0 {
		return nil
	}
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return &memosApiV1ResourcesGetResourceRequestFieldMaskPaths{
		fieldPath: fieldPath,
		prefix:    prefix,
		name:      prefix + "name",
	}
}

func (x *memosApiV1ResourcesGetResourceRequestFieldMaskPaths) String() string { return x.fieldPath }
func (x *memosApiV1ResourcesGetResourceRequestFieldMaskPaths) Name() string   { return x.name }

type memosApiV1ResourcesGetResourceByUidRequestIntFieldMaskPaths interface {
	Uid() string
}

type memosApiV1ResourcesGetResourceByUidRequestFieldMaskPaths struct {
	fieldPath string
	prefix    string
	uid       string
}

func newMemosApiV1ResourcesGetResourceByUidRequestFieldMaskPaths(fieldPath string, maxDepth int) *memosApiV1ResourcesGetResourceByUidRequestFieldMaskPaths {
	if maxDepth <= 0 {
		return nil
	}
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return &memosApiV1ResourcesGetResourceByUidRequestFieldMaskPaths{
		fieldPath: fieldPath,
		prefix:    prefix,
		uid:       prefix + "uid",
	}
}

func (x *memosApiV1ResourcesGetResourceByUidRequestFieldMaskPaths) String() string {
	return x.fieldPath
}
func (x *memosApiV1ResourcesGetResourceByUidRequestFieldMaskPaths) Uid() string { return x.uid }

type memosApiV1ResourcesGetResourceBinaryRequestIntFieldMaskPaths interface {
	Name() string
	Filename() string
	Thumbnail() string
}

type memosApiV1ResourcesGetResourceBinaryRequestFieldMaskPaths struct {
	fieldPath string
	prefix    string
	name      string
	filename  string
	thumbnail string
}

func newMemosApiV1ResourcesGetResourceBinaryRequestFieldMaskPaths(fieldPath string, maxDepth int) *memosApiV1ResourcesGetResourceBinaryRequestFieldMaskPaths {
	if maxDepth <= 0 {
		return nil
	}
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return &memosApiV1ResourcesGetResourceBinaryRequestFieldMaskPaths{
		fieldPath: fieldPath,
		prefix:    prefix,
		name:      prefix + "name",
		filename:  prefix + "filename",
		thumbnail: prefix + "thumbnail",
	}
}

func (x *memosApiV1ResourcesGetResourceBinaryRequestFieldMaskPaths) String() string {
	return x.fieldPath
}
func (x *memosApiV1ResourcesGetResourceBinaryRequestFieldMaskPaths) Name() string { return x.name }
func (x *memosApiV1ResourcesGetResourceBinaryRequestFieldMaskPaths) Filename() string {
	return x.filename
}
func (x *memosApiV1ResourcesGetResourceBinaryRequestFieldMaskPaths) Thumbnail() string {
	return x.thumbnail
}

type memosApiV1ResourcesUpdateResourceRequestIntFieldMaskPaths interface {
	Resource() *memosApiV1ResourcesResourceFieldMaskPaths
	UpdateMask() *googleProtobufFieldMaskFieldMaskPaths
}

type memosApiV1ResourcesUpdateResourceRequestFieldMaskPaths struct {
	fieldPath  string
	prefix     string
	resource   *memosApiV1ResourcesResourceFieldMaskPaths
	updateMask *googleProtobufFieldMaskFieldMaskPaths
}

func newMemosApiV1ResourcesUpdateResourceRequestFieldMaskPaths(fieldPath string, maxDepth int) *memosApiV1ResourcesUpdateResourceRequestFieldMaskPaths {
	if maxDepth <= 0 {
		return nil
	}
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return &memosApiV1ResourcesUpdateResourceRequestFieldMaskPaths{
		fieldPath:  fieldPath,
		prefix:     prefix,
		resource:   newMemosApiV1ResourcesResourceFieldMaskPaths(prefix+"resource", maxDepth-1),
		updateMask: newGoogleProtobufFieldMaskFieldMaskPaths(prefix+"update_mask", maxDepth-1),
	}
}

func (x *memosApiV1ResourcesUpdateResourceRequestFieldMaskPaths) String() string { return x.fieldPath }
func (x *memosApiV1ResourcesUpdateResourceRequestFieldMaskPaths) Resource() *memosApiV1ResourcesResourceFieldMaskPaths {
	if x.resource != nil {
		return x.resource
	}
	return newMemosApiV1ResourcesResourceFieldMaskPaths(x.prefix+"resource", 2)
}
func (x *memosApiV1ResourcesUpdateResourceRequestFieldMaskPaths) UpdateMask() *googleProtobufFieldMaskFieldMaskPaths {
	if x.updateMask != nil {
		return x.updateMask
	}
	return newGoogleProtobufFieldMaskFieldMaskPaths(x.prefix+"update_mask", 2)
}

type googleProtobufFieldMaskFieldMaskPaths struct {
	fieldPath string
	prefix    string
	paths     string
}

func newGoogleProtobufFieldMaskFieldMaskPaths(fieldPath string, maxDepth int) *googleProtobufFieldMaskFieldMaskPaths {
	if maxDepth <= 0 {
		return nil
	}
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return &googleProtobufFieldMaskFieldMaskPaths{
		fieldPath: fieldPath,
		prefix:    prefix,
		paths:     prefix + "paths",
	}
}

func (x *googleProtobufFieldMaskFieldMaskPaths) String() string { return x.fieldPath }
func (x *googleProtobufFieldMaskFieldMaskPaths) Paths() string  { return x.paths }

type memosApiV1ResourcesDeleteResourceRequestIntFieldMaskPaths interface {
	Name() string
}

type memosApiV1ResourcesDeleteResourceRequestFieldMaskPaths struct {
	fieldPath string
	prefix    string
	name      string
}

func newMemosApiV1ResourcesDeleteResourceRequestFieldMaskPaths(fieldPath string, maxDepth int) *memosApiV1ResourcesDeleteResourceRequestFieldMaskPaths {
	if maxDepth <= 0 {
		return nil
	}
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return &memosApiV1ResourcesDeleteResourceRequestFieldMaskPaths{
		fieldPath: fieldPath,
		prefix:    prefix,
		name:      prefix + "name",
	}
}

func (x *memosApiV1ResourcesDeleteResourceRequestFieldMaskPaths) String() string { return x.fieldPath }
func (x *memosApiV1ResourcesDeleteResourceRequestFieldMaskPaths) Name() string   { return x.name }
