//Code generated by protoc-gen-go-fieldmask. DO NOT EDIT.
//versions:
//- protoc-gen-go-fieldmask v1.0.9
//- protoc (unknown)
//source: api/v1/resources/resource_service.proto

package resources

import (
	fieldmask "github.com/RyoJerryYu/protoc-gen-plugins/pkg/fieldmask"
)

// IResourceFieldPath is the interface for the field path of Resource
type IResourceFieldPath interface {
	String() string
	Name() string
	Uid() string
	CreateTime() fieldmask.ITimestampFieldPath
	Filename() string
	Content() string
	ExternalLink() string
	Size() string
}

// resourceFieldPath is the implementation for the field path of Resource
type resourceFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewResourceFieldPath creates a new resourceFieldPath
func NewResourceFieldPath(fieldPath string) IResourceFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return resourceFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x resourceFieldPath) String() string { return x.fieldPath }

func (x resourceFieldPath) Name() string { return x.prefix + "name" }
func (x resourceFieldPath) Uid() string  { return x.prefix + "uid" }
func (x resourceFieldPath) CreateTime() fieldmask.ITimestampFieldPath {
	return fieldmask.NewTimestampFieldPath(x.prefix + "create_time")
}
func (x resourceFieldPath) Filename() string     { return x.prefix + "filename" }
func (x resourceFieldPath) Content() string      { return x.prefix + "content" }
func (x resourceFieldPath) ExternalLink() string { return x.prefix + "external_link" }
func (x resourceFieldPath) Size() string         { return x.prefix + "size" }

// FieldPath returns the field path for Resource
func (x *Resource) FieldPath() IResourceFieldPath {
	return NewResourceFieldPath("")
}

// ICreateResourceRequestFieldPath is the interface for the field path of CreateResourceRequest
type ICreateResourceRequestFieldPath interface {
	String() string
	Resource() IResourceFieldPath
}

// createResourceRequestFieldPath is the implementation for the field path of CreateResourceRequest
type createResourceRequestFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewCreateResourceRequestFieldPath creates a new createResourceRequestFieldPath
func NewCreateResourceRequestFieldPath(fieldPath string) ICreateResourceRequestFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return createResourceRequestFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x createResourceRequestFieldPath) String() string { return x.fieldPath }

func (x createResourceRequestFieldPath) Resource() IResourceFieldPath {
	return NewResourceFieldPath(x.prefix + "resource")
}

// FieldPath returns the field path for CreateResourceRequest
func (x *CreateResourceRequest) FieldPath() ICreateResourceRequestFieldPath {
	return NewCreateResourceRequestFieldPath("")
}

// IListResourcesRequestFieldPath is the interface for the field path of ListResourcesRequest
type IListResourcesRequestFieldPath interface {
	String() string
}

// listResourcesRequestFieldPath is the implementation for the field path of ListResourcesRequest
type listResourcesRequestFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewListResourcesRequestFieldPath creates a new listResourcesRequestFieldPath
func NewListResourcesRequestFieldPath(fieldPath string) IListResourcesRequestFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return listResourcesRequestFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x listResourcesRequestFieldPath) String() string { return x.fieldPath }

// FieldPath returns the field path for ListResourcesRequest
func (x *ListResourcesRequest) FieldPath() IListResourcesRequestFieldPath {
	return NewListResourcesRequestFieldPath("")
}

// IListResourcesResponseFieldPath is the interface for the field path of ListResourcesResponse
type IListResourcesResponseFieldPath interface {
	String() string
	Resources() string
}

// listResourcesResponseFieldPath is the implementation for the field path of ListResourcesResponse
type listResourcesResponseFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewListResourcesResponseFieldPath creates a new listResourcesResponseFieldPath
func NewListResourcesResponseFieldPath(fieldPath string) IListResourcesResponseFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return listResourcesResponseFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x listResourcesResponseFieldPath) String() string { return x.fieldPath }

func (x listResourcesResponseFieldPath) Resources() string { return x.prefix + "resources" }

// FieldPath returns the field path for ListResourcesResponse
func (x *ListResourcesResponse) FieldPath() IListResourcesResponseFieldPath {
	return NewListResourcesResponseFieldPath("")
}

// IGetResourceRequestFieldPath is the interface for the field path of GetResourceRequest
type IGetResourceRequestFieldPath interface {
	String() string
	Name() string
}

// getResourceRequestFieldPath is the implementation for the field path of GetResourceRequest
type getResourceRequestFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewGetResourceRequestFieldPath creates a new getResourceRequestFieldPath
func NewGetResourceRequestFieldPath(fieldPath string) IGetResourceRequestFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return getResourceRequestFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x getResourceRequestFieldPath) String() string { return x.fieldPath }

func (x getResourceRequestFieldPath) Name() string { return x.prefix + "name" }

// FieldPath returns the field path for GetResourceRequest
func (x *GetResourceRequest) FieldPath() IGetResourceRequestFieldPath {
	return NewGetResourceRequestFieldPath("")
}

// IGetResourceByUidRequestFieldPath is the interface for the field path of GetResourceByUidRequest
type IGetResourceByUidRequestFieldPath interface {
	String() string
	Uid() string
}

// getResourceByUidRequestFieldPath is the implementation for the field path of GetResourceByUidRequest
type getResourceByUidRequestFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewGetResourceByUidRequestFieldPath creates a new getResourceByUidRequestFieldPath
func NewGetResourceByUidRequestFieldPath(fieldPath string) IGetResourceByUidRequestFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return getResourceByUidRequestFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x getResourceByUidRequestFieldPath) String() string { return x.fieldPath }

func (x getResourceByUidRequestFieldPath) Uid() string { return x.prefix + "uid" }

// FieldPath returns the field path for GetResourceByUidRequest
func (x *GetResourceByUidRequest) FieldPath() IGetResourceByUidRequestFieldPath {
	return NewGetResourceByUidRequestFieldPath("")
}

// IGetResourceBinaryRequestFieldPath is the interface for the field path of GetResourceBinaryRequest
type IGetResourceBinaryRequestFieldPath interface {
	String() string
	Name() string
	Filename() string
	Thumbnail() string
}

// getResourceBinaryRequestFieldPath is the implementation for the field path of GetResourceBinaryRequest
type getResourceBinaryRequestFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewGetResourceBinaryRequestFieldPath creates a new getResourceBinaryRequestFieldPath
func NewGetResourceBinaryRequestFieldPath(fieldPath string) IGetResourceBinaryRequestFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return getResourceBinaryRequestFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x getResourceBinaryRequestFieldPath) String() string { return x.fieldPath }

func (x getResourceBinaryRequestFieldPath) Name() string      { return x.prefix + "name" }
func (x getResourceBinaryRequestFieldPath) Filename() string  { return x.prefix + "filename" }
func (x getResourceBinaryRequestFieldPath) Thumbnail() string { return x.prefix + "thumbnail" }

// FieldPath returns the field path for GetResourceBinaryRequest
func (x *GetResourceBinaryRequest) FieldPath() IGetResourceBinaryRequestFieldPath {
	return NewGetResourceBinaryRequestFieldPath("")
}

// IUpdateResourceRequestFieldPath is the interface for the field path of UpdateResourceRequest
type IUpdateResourceRequestFieldPath interface {
	String() string
	Resource() IResourceFieldPath
	UpdateMask() fieldmask.IFieldMaskFieldPath
}

// updateResourceRequestFieldPath is the implementation for the field path of UpdateResourceRequest
type updateResourceRequestFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewUpdateResourceRequestFieldPath creates a new updateResourceRequestFieldPath
func NewUpdateResourceRequestFieldPath(fieldPath string) IUpdateResourceRequestFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return updateResourceRequestFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x updateResourceRequestFieldPath) String() string { return x.fieldPath }

func (x updateResourceRequestFieldPath) Resource() IResourceFieldPath {
	return NewResourceFieldPath(x.prefix + "resource")
}
func (x updateResourceRequestFieldPath) UpdateMask() fieldmask.IFieldMaskFieldPath {
	return fieldmask.NewFieldMaskFieldPath(x.prefix + "update_mask")
}

// FieldPath returns the field path for UpdateResourceRequest
func (x *UpdateResourceRequest) FieldPath() IUpdateResourceRequestFieldPath {
	return NewUpdateResourceRequestFieldPath("")
}

// IDeleteResourceRequestFieldPath is the interface for the field path of DeleteResourceRequest
type IDeleteResourceRequestFieldPath interface {
	String() string
	Name() string
}

// deleteResourceRequestFieldPath is the implementation for the field path of DeleteResourceRequest
type deleteResourceRequestFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewDeleteResourceRequestFieldPath creates a new deleteResourceRequestFieldPath
func NewDeleteResourceRequestFieldPath(fieldPath string) IDeleteResourceRequestFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return deleteResourceRequestFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x deleteResourceRequestFieldPath) String() string { return x.fieldPath }

func (x deleteResourceRequestFieldPath) Name() string { return x.prefix + "name" }

// FieldPath returns the field path for DeleteResourceRequest
func (x *DeleteResourceRequest) FieldPath() IDeleteResourceRequestFieldPath {
	return NewDeleteResourceRequestFieldPath("")
}
