//Code generated by protoc-gen-go-fieldmask. DO NOT EDIT.
//versions:
//- protoc-gen-go-fieldmask v1.0.9
//- protoc (unknown)
//source: store/inbox.proto

package store

// IInboxMessageFieldPath is the interface for the field path of InboxMessage
type IInboxMessageFieldPath interface {
	String() string
}

// inboxMessageFieldPath is the implementation for the field path of InboxMessage
type inboxMessageFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewInboxMessageFieldPath creates a new inboxMessageFieldPath
func NewInboxMessageFieldPath(fieldPath string) IInboxMessageFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return inboxMessageFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x inboxMessageFieldPath) String() string { return x.fieldPath }

// FieldPath returns the field path for InboxMessage
func (x *InboxMessage) FieldPath() IInboxMessageFieldPath {
	return NewInboxMessageFieldPath("")
}
