// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: store/memo.proto

package store

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on MemoPayload with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MemoPayload) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MemoPayload with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MemoPayloadMultiError, or
// nil if none found.
func (m *MemoPayload) ValidateAll() error {
	return m.validate(true)
}

func (m *MemoPayload) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetProperty()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MemoPayloadValidationError{
					field:  "Property",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MemoPayloadValidationError{
					field:  "Property",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProperty()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MemoPayloadValidationError{
				field:  "Property",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetLocation()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MemoPayloadValidationError{
					field:  "Location",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MemoPayloadValidationError{
					field:  "Location",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLocation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MemoPayloadValidationError{
				field:  "Location",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MemoPayloadMultiError(errors)
	}

	return nil
}

// MemoPayloadMultiError is an error wrapping multiple validation errors
// returned by MemoPayload.ValidateAll() if the designated constraints aren't met.
type MemoPayloadMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MemoPayloadMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MemoPayloadMultiError) AllErrors() []error { return m }

// MemoPayloadValidationError is the validation error returned by
// MemoPayload.Validate if the designated constraints aren't met.
type MemoPayloadValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MemoPayloadValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MemoPayloadValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MemoPayloadValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MemoPayloadValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MemoPayloadValidationError) ErrorName() string { return "MemoPayloadValidationError" }

// Error satisfies the builtin error interface
func (e MemoPayloadValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMemoPayload.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MemoPayloadValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MemoPayloadValidationError{}

// Validate checks the field values on MemoPayload_Property with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MemoPayload_Property) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MemoPayload_Property with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MemoPayload_PropertyMultiError, or nil if none found.
func (m *MemoPayload_Property) ValidateAll() error {
	return m.validate(true)
}

func (m *MemoPayload_Property) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for HasLink

	// no validation rules for HasTaskList

	// no validation rules for HasCode

	// no validation rules for HasIncompleteTasks

	if len(errors) > 0 {
		return MemoPayload_PropertyMultiError(errors)
	}

	return nil
}

// MemoPayload_PropertyMultiError is an error wrapping multiple validation
// errors returned by MemoPayload_Property.ValidateAll() if the designated
// constraints aren't met.
type MemoPayload_PropertyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MemoPayload_PropertyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MemoPayload_PropertyMultiError) AllErrors() []error { return m }

// MemoPayload_PropertyValidationError is the validation error returned by
// MemoPayload_Property.Validate if the designated constraints aren't met.
type MemoPayload_PropertyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MemoPayload_PropertyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MemoPayload_PropertyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MemoPayload_PropertyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MemoPayload_PropertyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MemoPayload_PropertyValidationError) ErrorName() string {
	return "MemoPayload_PropertyValidationError"
}

// Error satisfies the builtin error interface
func (e MemoPayload_PropertyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMemoPayload_Property.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MemoPayload_PropertyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MemoPayload_PropertyValidationError{}

// Validate checks the field values on MemoPayload_Location with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MemoPayload_Location) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MemoPayload_Location with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MemoPayload_LocationMultiError, or nil if none found.
func (m *MemoPayload_Location) ValidateAll() error {
	return m.validate(true)
}

func (m *MemoPayload_Location) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Placeholder

	// no validation rules for Latitude

	// no validation rules for Longitude

	if len(errors) > 0 {
		return MemoPayload_LocationMultiError(errors)
	}

	return nil
}

// MemoPayload_LocationMultiError is an error wrapping multiple validation
// errors returned by MemoPayload_Location.ValidateAll() if the designated
// constraints aren't met.
type MemoPayload_LocationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MemoPayload_LocationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MemoPayload_LocationMultiError) AllErrors() []error { return m }

// MemoPayload_LocationValidationError is the validation error returned by
// MemoPayload_Location.Validate if the designated constraints aren't met.
type MemoPayload_LocationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MemoPayload_LocationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MemoPayload_LocationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MemoPayload_LocationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MemoPayload_LocationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MemoPayload_LocationValidationError) ErrorName() string {
	return "MemoPayload_LocationValidationError"
}

// Error satisfies the builtin error interface
func (e MemoPayload_LocationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMemoPayload_Location.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MemoPayload_LocationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MemoPayload_LocationValidationError{}
