//Code generated by protoc-gen-go-fieldmask. DO NOT EDIT.
//versions:
//- protoc-gen-go-fieldmask v1.0.9
//- protoc (unknown)
//source: store/memo.proto

package store

// IMemoPayloadFieldPath is the interface for the field path of MemoPayload
type IMemoPayloadFieldPath interface {
	String() string
	Property() IMemoPayload_PropertyFieldPath
	Location() IMemoPayload_LocationFieldPath
}

// memoPayloadFieldPath is the implementation for the field path of MemoPayload
type memoPayloadFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewMemoPayloadFieldPath creates a new memoPayloadFieldPath
func NewMemoPayloadFieldPath(fieldPath string) IMemoPayloadFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return memoPayloadFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x memoPayloadFieldPath) String() string { return x.fieldPath }

func (x memoPayloadFieldPath) Property() IMemoPayload_PropertyFieldPath {
	return NewMemoPayload_PropertyFieldPath(x.prefix + "property")
}
func (x memoPayloadFieldPath) Location() IMemoPayload_LocationFieldPath {
	return NewMemoPayload_LocationFieldPath(x.prefix + "location")
}

// FieldPath returns the field path for MemoPayload
func (x *MemoPayload) FieldPath() IMemoPayloadFieldPath {
	return NewMemoPayloadFieldPath("")
}

// IMemoPayload_PropertyFieldPath is the interface for the field path of MemoPayload_Property
type IMemoPayload_PropertyFieldPath interface {
	String() string
	Tags() string
	HasLink() string
	HasTaskList() string
	HasCode() string
	HasIncompleteTasks() string
}

// memoPayload_PropertyFieldPath is the implementation for the field path of MemoPayload_Property
type memoPayload_PropertyFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewMemoPayload_PropertyFieldPath creates a new memoPayload_PropertyFieldPath
func NewMemoPayload_PropertyFieldPath(fieldPath string) IMemoPayload_PropertyFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return memoPayload_PropertyFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x memoPayload_PropertyFieldPath) String() string { return x.fieldPath }

func (x memoPayload_PropertyFieldPath) Tags() string        { return x.prefix + "tags" }
func (x memoPayload_PropertyFieldPath) HasLink() string     { return x.prefix + "has_link" }
func (x memoPayload_PropertyFieldPath) HasTaskList() string { return x.prefix + "has_task_list" }
func (x memoPayload_PropertyFieldPath) HasCode() string     { return x.prefix + "has_code" }
func (x memoPayload_PropertyFieldPath) HasIncompleteTasks() string {
	return x.prefix + "has_incomplete_tasks"
}

// FieldPath returns the field path for MemoPayload_Property
func (x *MemoPayload_Property) FieldPath() IMemoPayload_PropertyFieldPath {
	return NewMemoPayload_PropertyFieldPath("")
}

// IMemoPayload_LocationFieldPath is the interface for the field path of MemoPayload_Location
type IMemoPayload_LocationFieldPath interface {
	String() string
	Placeholder() string
	Latitude() string
	Longitude() string
}

// memoPayload_LocationFieldPath is the implementation for the field path of MemoPayload_Location
type memoPayload_LocationFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewMemoPayload_LocationFieldPath creates a new memoPayload_LocationFieldPath
func NewMemoPayload_LocationFieldPath(fieldPath string) IMemoPayload_LocationFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return memoPayload_LocationFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x memoPayload_LocationFieldPath) String() string { return x.fieldPath }

func (x memoPayload_LocationFieldPath) Placeholder() string { return x.prefix + "placeholder" }
func (x memoPayload_LocationFieldPath) Latitude() string    { return x.prefix + "latitude" }
func (x memoPayload_LocationFieldPath) Longitude() string   { return x.prefix + "longitude" }

// FieldPath returns the field path for MemoPayload_Location
func (x *MemoPayload_Location) FieldPath() IMemoPayload_LocationFieldPath {
	return NewMemoPayload_LocationFieldPath("")
}
