//Code generated by protoc-gen-go-fieldmask. DO NOT EDIT.
//versions:
//- protoc-gen-go-fieldmask v1.0.9
//- protoc (unknown)
//source: store/resource.proto

package store

import (
	fieldmask "github.com/RyoJerryYu/protoc-gen-plugins/pkg/fieldmask"
)

// IResourcePayloadFieldPath is the interface for the field path of ResourcePayload
type IResourcePayloadFieldPath interface {
	String() string
	S3Object() IResourcePayload_S3ObjectFieldPath
}

// resourcePayloadFieldPath is the implementation for the field path of ResourcePayload
type resourcePayloadFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewResourcePayloadFieldPath creates a new resourcePayloadFieldPath
func NewResourcePayloadFieldPath(fieldPath string) IResourcePayloadFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return resourcePayloadFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x resourcePayloadFieldPath) String() string { return x.fieldPath }

func (x resourcePayloadFieldPath) S3Object() IResourcePayload_S3ObjectFieldPath {
	return NewResourcePayload_S3ObjectFieldPath(x.prefix + "s3_object")
}

// FieldPath returns the field path for ResourcePayload
func (x *ResourcePayload) FieldPath() IResourcePayloadFieldPath {
	return NewResourcePayloadFieldPath("")
}

// IResourcePayload_S3ObjectFieldPath is the interface for the field path of ResourcePayload_S3Object
type IResourcePayload_S3ObjectFieldPath interface {
	String() string
	S3Config() IStorageS3ConfigFieldPath
	Key() string
	LastPresignedTime() fieldmask.ITimestampFieldPath
}

// resourcePayload_S3ObjectFieldPath is the implementation for the field path of ResourcePayload_S3Object
type resourcePayload_S3ObjectFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewResourcePayload_S3ObjectFieldPath creates a new resourcePayload_S3ObjectFieldPath
func NewResourcePayload_S3ObjectFieldPath(fieldPath string) IResourcePayload_S3ObjectFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return resourcePayload_S3ObjectFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x resourcePayload_S3ObjectFieldPath) String() string { return x.fieldPath }

func (x resourcePayload_S3ObjectFieldPath) S3Config() IStorageS3ConfigFieldPath {
	return NewStorageS3ConfigFieldPath(x.prefix + "s3_config")
}
func (x resourcePayload_S3ObjectFieldPath) Key() string { return x.prefix + "key" }
func (x resourcePayload_S3ObjectFieldPath) LastPresignedTime() fieldmask.ITimestampFieldPath {
	return fieldmask.NewTimestampFieldPath(x.prefix + "last_presigned_time")
}

// FieldPath returns the field path for ResourcePayload_S3Object
func (x *ResourcePayload_S3Object) FieldPath() IResourcePayload_S3ObjectFieldPath {
	return NewResourcePayload_S3ObjectFieldPath("")
}
