//Code generated by protoc-gen-go-fieldmask. DO NOT EDIT.
//versions:
//- protoc-gen-go-fieldmask v1.0.9
//- protoc (unknown)
//source: store/user_setting.proto

package store

// IUserSettingFieldPath is the interface for the field path of UserSetting
type IUserSettingFieldPath interface {
	String() string
	UserId() string
	Key() string
	AccessTokens() IAccessTokensUserSettingFieldPath
	Locale() string
	Appearance() string
	MemoVisibility() string
}

// userSettingFieldPath is the implementation for the field path of UserSetting
type userSettingFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewUserSettingFieldPath creates a new userSettingFieldPath
func NewUserSettingFieldPath(fieldPath string) IUserSettingFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return userSettingFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x userSettingFieldPath) String() string { return x.fieldPath }

func (x userSettingFieldPath) UserId() string { return x.prefix + "user_id" }
func (x userSettingFieldPath) Key() string    { return x.prefix + "key" }
func (x userSettingFieldPath) AccessTokens() IAccessTokensUserSettingFieldPath {
	return NewAccessTokensUserSettingFieldPath(x.prefix + "access_tokens")
}
func (x userSettingFieldPath) Locale() string         { return x.prefix + "locale" }
func (x userSettingFieldPath) Appearance() string     { return x.prefix + "appearance" }
func (x userSettingFieldPath) MemoVisibility() string { return x.prefix + "memo_visibility" }

// FieldPath returns the field path for UserSetting
func (x *UserSetting) FieldPath() IUserSettingFieldPath {
	return NewUserSettingFieldPath("")
}

// IAccessTokensUserSettingFieldPath is the interface for the field path of AccessTokensUserSetting
type IAccessTokensUserSettingFieldPath interface {
	String() string
	AccessTokens() string
}

// accessTokensUserSettingFieldPath is the implementation for the field path of AccessTokensUserSetting
type accessTokensUserSettingFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewAccessTokensUserSettingFieldPath creates a new accessTokensUserSettingFieldPath
func NewAccessTokensUserSettingFieldPath(fieldPath string) IAccessTokensUserSettingFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return accessTokensUserSettingFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x accessTokensUserSettingFieldPath) String() string { return x.fieldPath }

func (x accessTokensUserSettingFieldPath) AccessTokens() string { return x.prefix + "access_tokens" }

// FieldPath returns the field path for AccessTokensUserSetting
func (x *AccessTokensUserSetting) FieldPath() IAccessTokensUserSettingFieldPath {
	return NewAccessTokensUserSettingFieldPath("")
}

// IAccessTokensUserSetting_AccessTokenFieldPath is the interface for the field path of AccessTokensUserSetting_AccessToken
type IAccessTokensUserSetting_AccessTokenFieldPath interface {
	String() string
	AccessToken() string
	Description() string
}

// accessTokensUserSetting_AccessTokenFieldPath is the implementation for the field path of AccessTokensUserSetting_AccessToken
type accessTokensUserSetting_AccessTokenFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewAccessTokensUserSetting_AccessTokenFieldPath creates a new accessTokensUserSetting_AccessTokenFieldPath
func NewAccessTokensUserSetting_AccessTokenFieldPath(fieldPath string) IAccessTokensUserSetting_AccessTokenFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return accessTokensUserSetting_AccessTokenFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x accessTokensUserSetting_AccessTokenFieldPath) String() string { return x.fieldPath }

func (x accessTokensUserSetting_AccessTokenFieldPath) AccessToken() string {
	return x.prefix + "access_token"
}
func (x accessTokensUserSetting_AccessTokenFieldPath) Description() string {
	return x.prefix + "description"
}

// FieldPath returns the field path for AccessTokensUserSetting_AccessToken
func (x *AccessTokensUserSetting_AccessToken) FieldPath() IAccessTokensUserSetting_AccessTokenFieldPath {
	return NewAccessTokensUserSetting_AccessTokenFieldPath("")
}
