// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: store/user_setting.proto

package store

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserSetting with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserSetting) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserSetting with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserSettingMultiError, or
// nil if none found.
func (m *UserSetting) ValidateAll() error {
	return m.validate(true)
}

func (m *UserSetting) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Key

	switch v := m.Value.(type) {
	case *UserSetting_AccessTokens:
		if v == nil {
			err := UserSettingValidationError{
				field:  "Value",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetAccessTokens()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserSettingValidationError{
						field:  "AccessTokens",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserSettingValidationError{
						field:  "AccessTokens",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetAccessTokens()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserSettingValidationError{
					field:  "AccessTokens",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *UserSetting_Locale:
		if v == nil {
			err := UserSettingValidationError{
				field:  "Value",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Locale
	case *UserSetting_Appearance:
		if v == nil {
			err := UserSettingValidationError{
				field:  "Value",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Appearance
	case *UserSetting_MemoVisibility:
		if v == nil {
			err := UserSettingValidationError{
				field:  "Value",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for MemoVisibility
	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return UserSettingMultiError(errors)
	}

	return nil
}

// UserSettingMultiError is an error wrapping multiple validation errors
// returned by UserSetting.ValidateAll() if the designated constraints aren't met.
type UserSettingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserSettingMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserSettingMultiError) AllErrors() []error { return m }

// UserSettingValidationError is the validation error returned by
// UserSetting.Validate if the designated constraints aren't met.
type UserSettingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserSettingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserSettingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserSettingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserSettingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserSettingValidationError) ErrorName() string { return "UserSettingValidationError" }

// Error satisfies the builtin error interface
func (e UserSettingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserSetting.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserSettingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserSettingValidationError{}

// Validate checks the field values on AccessTokensUserSetting with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AccessTokensUserSetting) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AccessTokensUserSetting with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AccessTokensUserSettingMultiError, or nil if none found.
func (m *AccessTokensUserSetting) ValidateAll() error {
	return m.validate(true)
}

func (m *AccessTokensUserSetting) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetAccessTokens() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AccessTokensUserSettingValidationError{
						field:  fmt.Sprintf("AccessTokens[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AccessTokensUserSettingValidationError{
						field:  fmt.Sprintf("AccessTokens[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AccessTokensUserSettingValidationError{
					field:  fmt.Sprintf("AccessTokens[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return AccessTokensUserSettingMultiError(errors)
	}

	return nil
}

// AccessTokensUserSettingMultiError is an error wrapping multiple validation
// errors returned by AccessTokensUserSetting.ValidateAll() if the designated
// constraints aren't met.
type AccessTokensUserSettingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AccessTokensUserSettingMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AccessTokensUserSettingMultiError) AllErrors() []error { return m }

// AccessTokensUserSettingValidationError is the validation error returned by
// AccessTokensUserSetting.Validate if the designated constraints aren't met.
type AccessTokensUserSettingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessTokensUserSettingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessTokensUserSettingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessTokensUserSettingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessTokensUserSettingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessTokensUserSettingValidationError) ErrorName() string {
	return "AccessTokensUserSettingValidationError"
}

// Error satisfies the builtin error interface
func (e AccessTokensUserSettingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccessTokensUserSetting.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessTokensUserSettingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessTokensUserSettingValidationError{}

// Validate checks the field values on AccessTokensUserSetting_AccessToken with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *AccessTokensUserSetting_AccessToken) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AccessTokensUserSetting_AccessToken
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// AccessTokensUserSetting_AccessTokenMultiError, or nil if none found.
func (m *AccessTokensUserSetting_AccessToken) ValidateAll() error {
	return m.validate(true)
}

func (m *AccessTokensUserSetting_AccessToken) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccessToken

	// no validation rules for Description

	if len(errors) > 0 {
		return AccessTokensUserSetting_AccessTokenMultiError(errors)
	}

	return nil
}

// AccessTokensUserSetting_AccessTokenMultiError is an error wrapping multiple
// validation errors returned by
// AccessTokensUserSetting_AccessToken.ValidateAll() if the designated
// constraints aren't met.
type AccessTokensUserSetting_AccessTokenMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AccessTokensUserSetting_AccessTokenMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AccessTokensUserSetting_AccessTokenMultiError) AllErrors() []error { return m }

// AccessTokensUserSetting_AccessTokenValidationError is the validation error
// returned by AccessTokensUserSetting_AccessToken.Validate if the designated
// constraints aren't met.
type AccessTokensUserSetting_AccessTokenValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccessTokensUserSetting_AccessTokenValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccessTokensUserSetting_AccessTokenValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccessTokensUserSetting_AccessTokenValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccessTokensUserSetting_AccessTokenValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccessTokensUserSetting_AccessTokenValidationError) ErrorName() string {
	return "AccessTokensUserSetting_AccessTokenValidationError"
}

// Error satisfies the builtin error interface
func (e AccessTokensUserSetting_AccessTokenValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccessTokensUserSetting_AccessToken.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccessTokensUserSetting_AccessTokenValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccessTokensUserSetting_AccessTokenValidationError{}
