//Code generated by protoc-gen-go-fieldmask. DO NOT EDIT.
//versions:
//- protoc-gen-go-fieldmask v1.0.9
//- protoc (unknown)
//source: api/v1/memos/memo_relation_service.proto

package memos

// IMemoRelationFieldPath is the interface for the field path of MemoRelation
type IMemoRelationFieldPath interface {
	String() string
	Memo() IMemoRelation_MemoFieldPath
	RelatedMemo() IMemoRelation_MemoFieldPath
}

// memoRelationFieldPath is the implementation for the field path of MemoRelation
type memoRelationFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewMemoRelationFieldPath creates a new memoRelationFieldPath
func NewMemoRelationFieldPath(fieldPath string) IMemoRelationFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return memoRelationFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x memoRelationFieldPath) String() string { return x.fieldPath }

func (x memoRelationFieldPath) Memo() IMemoRelation_MemoFieldPath {
	return NewMemoRelation_MemoFieldPath(x.prefix + "memo")
}
func (x memoRelationFieldPath) RelatedMemo() IMemoRelation_MemoFieldPath {
	return NewMemoRelation_MemoFieldPath(x.prefix + "related_memo")
}

// FieldPath returns the field path for MemoRelation
func (x *MemoRelation) FieldPath() IMemoRelationFieldPath {
	return NewMemoRelationFieldPath("")
}

// IMemoRelation_MemoFieldPath is the interface for the field path of MemoRelation_Memo
type IMemoRelation_MemoFieldPath interface {
	String() string
	Name() string
	Uid() string
	Snippet() string
}

// memoRelation_MemoFieldPath is the implementation for the field path of MemoRelation_Memo
type memoRelation_MemoFieldPath struct {
	fieldPath string // the field path to the current field, empty if it's root
	prefix    string // e.g. "fieldPath." or empty if it's root
}

// NewMemoRelation_MemoFieldPath creates a new memoRelation_MemoFieldPath
func NewMemoRelation_MemoFieldPath(fieldPath string) IMemoRelation_MemoFieldPath {
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return memoRelation_MemoFieldPath{fieldPath: fieldPath, prefix: prefix}
}

// String returns the field path
func (x memoRelation_MemoFieldPath) String() string { return x.fieldPath }

func (x memoRelation_MemoFieldPath) Name() string    { return x.prefix + "name" }
func (x memoRelation_MemoFieldPath) Uid() string     { return x.prefix + "uid" }
func (x memoRelation_MemoFieldPath) Snippet() string { return x.prefix + "snippet" }

// FieldPath returns the field path for MemoRelation_Memo
func (x *MemoRelation_Memo) FieldPath() IMemoRelation_MemoFieldPath {
	return NewMemoRelation_MemoFieldPath("")
}
