// Code generated by protoc-gen-fieldmask. DO NOT EDIT.
// source: api/v1/memos/memo_relation_service.proto
package memos

var localMemosApiV1MemosMemoRelationFieldMaskPaths = newMemosApiV1MemosMemoRelationFieldMaskPaths("", 2)
var localMemosApiV1MemosMemoRelationMemoRelationMemoFieldMaskPaths = newMemosApiV1MemosMemoRelationMemoRelationMemoFieldMaskPaths("", 2)

func (x *MemoRelation) FieldMaskPaths() memosApiV1MemosMemoRelationIntFieldMaskPaths {
	return localMemosApiV1MemosMemoRelationFieldMaskPaths
}
func (x *MemoRelation_Memo) FieldMaskPaths() memosApiV1MemosMemoRelationMemoRelation_MemoIntFieldMaskPaths {
	return localMemosApiV1MemosMemoRelationMemoRelationMemoFieldMaskPaths
}

type memosApiV1MemosMemoRelationIntFieldMaskPaths interface {
	Memo() *memosApiV1MemosMemoRelationMemoRelation_MemoFieldMaskPaths
	RelatedMemo() *memosApiV1MemosMemoRelationMemoRelation_MemoFieldMaskPaths
}

type memosApiV1MemosMemoRelationFieldMaskPaths struct {
	fieldPath   string
	prefix      string
	memo        *memosApiV1MemosMemoRelationMemoRelation_MemoFieldMaskPaths
	relatedMemo *memosApiV1MemosMemoRelationMemoRelation_MemoFieldMaskPaths
}

func newMemosApiV1MemosMemoRelationFieldMaskPaths(fieldPath string, maxDepth int) *memosApiV1MemosMemoRelationFieldMaskPaths {
	if maxDepth <= 0 {
		return nil
	}
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return &memosApiV1MemosMemoRelationFieldMaskPaths{
		fieldPath:   fieldPath,
		prefix:      prefix,
		memo:        newMemosApiV1MemosMemoRelationMemoRelationMemoFieldMaskPaths(prefix+"memo", maxDepth-1),
		relatedMemo: newMemosApiV1MemosMemoRelationMemoRelationMemoFieldMaskPaths(prefix+"related_memo", maxDepth-1),
	}
}

func (x *memosApiV1MemosMemoRelationFieldMaskPaths) String() string { return x.fieldPath }
func (x *memosApiV1MemosMemoRelationFieldMaskPaths) Memo() *memosApiV1MemosMemoRelationMemoRelation_MemoFieldMaskPaths {
	if x.memo != nil {
		return x.memo
	}
	return newMemosApiV1MemosMemoRelationMemoRelationMemoFieldMaskPaths(x.prefix+"memo", 2)
}
func (x *memosApiV1MemosMemoRelationFieldMaskPaths) RelatedMemo() *memosApiV1MemosMemoRelationMemoRelation_MemoFieldMaskPaths {
	if x.relatedMemo != nil {
		return x.relatedMemo
	}
	return newMemosApiV1MemosMemoRelationMemoRelationMemoFieldMaskPaths(x.prefix+"related_memo", 2)
}

type memosApiV1MemosMemoRelationMemoRelation_MemoIntFieldMaskPaths interface {
	Name() string
	Uid() string
	Snippet() string
}

type memosApiV1MemosMemoRelationMemoRelation_MemoFieldMaskPaths struct {
	fieldPath string
	prefix    string
	name      string
	uid       string
	snippet   string
}

func newMemosApiV1MemosMemoRelationMemoRelationMemoFieldMaskPaths(fieldPath string, maxDepth int) *memosApiV1MemosMemoRelationMemoRelation_MemoFieldMaskPaths {
	if maxDepth <= 0 {
		return nil
	}
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return &memosApiV1MemosMemoRelationMemoRelation_MemoFieldMaskPaths{
		fieldPath: fieldPath,
		prefix:    prefix,
		name:      prefix + "name",
		uid:       prefix + "uid",
		snippet:   prefix + "snippet",
	}
}

func (x *memosApiV1MemosMemoRelationMemoRelation_MemoFieldMaskPaths) String() string {
	return x.fieldPath
}
func (x *memosApiV1MemosMemoRelationMemoRelation_MemoFieldMaskPaths) Name() string { return x.name }
func (x *memosApiV1MemosMemoRelationMemoRelation_MemoFieldMaskPaths) Uid() string  { return x.uid }
func (x *memosApiV1MemosMemoRelationMemoRelation_MemoFieldMaskPaths) Snippet() string {
	return x.snippet
}
