// Code generated by protoc-gen-fieldmask. DO NOT EDIT.
// source: api/v1/memos/reaction_service.proto
package memos

var localMemosApiV1MemosReactionFieldMaskPaths = newMemosApiV1MemosReactionFieldMaskPaths("", 2)

func (x *Reaction) FieldMaskPaths() memosApiV1MemosReactionIntFieldMaskPaths {
	return localMemosApiV1MemosReactionFieldMaskPaths
}

type memosApiV1MemosReactionIntFieldMaskPaths interface {
	Id() string
	Creator() string
	ContentId() string
	ReactionType() string
}

type memosApiV1MemosReactionFieldMaskPaths struct {
	fieldPath    string
	prefix       string
	id           string
	creator      string
	contentId    string
	reactionType string
}

func newMemosApiV1MemosReactionFieldMaskPaths(fieldPath string, maxDepth int) *memosApiV1MemosReactionFieldMaskPaths {
	if maxDepth <= 0 {
		return nil
	}
	prefix := ""
	if fieldPath != "" {
		prefix = fieldPath + "."
	}
	return &memosApiV1MemosReactionFieldMaskPaths{
		fieldPath:    fieldPath,
		prefix:       prefix,
		id:           prefix + "id",
		creator:      prefix + "creator",
		contentId:    prefix + "content_id",
		reactionType: prefix + "reaction_type",
	}
}

func (x *memosApiV1MemosReactionFieldMaskPaths) String() string       { return x.fieldPath }
func (x *memosApiV1MemosReactionFieldMaskPaths) Id() string           { return x.id }
func (x *memosApiV1MemosReactionFieldMaskPaths) Creator() string      { return x.creator }
func (x *memosApiV1MemosReactionFieldMaskPaths) ContentId() string    { return x.contentId }
func (x *memosApiV1MemosReactionFieldMaskPaths) ReactionType() string { return x.reactionType }
